{% set name = "textual-plotext" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/textual_plotext-{{ version }}.tar.gz
  sha256: 6e8e608ca9da52b4f171fa4adb0e80cbcd8e668f1334e9e4d7fbfd064d393a4f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7.2
    - pip
    - poetry-core
  run:
    - python >=3.7.2
    - plotext >=5.2.8,<6.0.0
    - textual >=0.40.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - textual_plotext

about:
  home: https://github.com/Textualize/textual-plotext
  summary: A Textual widget wrapper library for Plotext
  dev_url: https://github.com/Textualize/textual-plotext
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
